### ISSUE TITLE
Unraid docker container not working with new update. 

### ISSUE THREAD

**Issue by guythnick** [mikenowak/docker-nrpe#1]
Have been running your container on my Unraid system for many months without issue.  After the most recent update, I am now getting these errors with the container.  My Nagios box cannot contact the system since the process isn't running.

```
Warning: Cannot open log file '/var/log/nrpe.log' for writing
Error: Unable to start nrpe daemon...
grep: /proc//status: No such file or directory
NRPE: (running)...
```

**Comment by mikenowak** [comment]
Hi, I believe the process is running, and we just cant read the log file - I will update that today.

Also, you say that you cannot connect to this NRPE instance, so can I ask how exactly you are querying the NRPE from your monitoring host? 

`check_nrpe ...`

**Comment by guythnick** [comment]
I just started my Nagios VM, and it is now working.  Not sure what changed... but this might have been a false alarm. 
There's about 10 checks I run on that box, for example one is a memory check:

![image](https://user-images.githubusercontent.com/5290202/144249942-851cbc77-3ffd-44e9-a50b-91d5a1cc9587.png)
